apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: hello-world
 name: hello-world
 namespace: default
spec:
 selector:
   matchLabels:
     app: hello-world
 replicas: 1
 template:
   metadata:
     labels:
       app: hello-world
   spec:
     containers:
     - image: registry.ng.bluemix.net/dns_namespace/hello-world:latest
       name: hello-world
---
apiVersion: v1
kind: Service
metadata:
 name: hello-world-nodeport
 labels:
   app: hello-world
spec:
 selector:
   app: hello-world
 type: NodePort
 ports:
  - port: 5000
    nodePort: 30871
